apiVersion: storage.kubesphere.io/v1alpha1
kind: Accessor
metadata:
  name: csi-qingcloud-accessor
spec:
  storage_class_name: "csi-qingcloud"
  global_rule:
    allowed_namespace: []
    allowed_workspace: []
  group_rule:
    - name: "test"
      allow_namespace: []
      allow_workspace: []
      field: "Label"
      key: "test"
      value: ["val"]