apiVersion: storage.kubesphere.io/v1alpha1
kind: Accessor
metadata:
  name: csi-qingcloud-accessor
spec:
  storage_class_name: "csi-qingcloud"
  namespace_selector:
    field_selector:
      - fieldExpressions:
          - field: "Name"
            operator: "In"
            values: ["default", ""]
    label_selector:
      - matchExpressions:
          - key: "app"
            operator: "In"
            values: "test-accessor"