apiVersion: storage.kubesphere.io/v1alpha1
kind: Accessor
metadata:
  name: csi-qingcloud-accessor
spec:
  # Add fields here
  storage_class: "csi-qingcloud"
  allowed_namespace: ["default"]
  allowed_workspace: ["system-workspace"]
