# permissions for end users to edit storageclassaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageclassaccess-editor-role
rules:
- apiGroups:
  - storage.kubesphere.io
  resources:
  - storageclassaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.kubesphere.io
  resources:
  - storageclassaccesses/status
  verbs:
  - get
